### ISSUE TITLE
Move to JuliaLang

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/AppleAccelerate.jl#3]
Shall we move this to JuliaLang, so that openlibm, Yeppp, VML and AppleAccelerate all together, and we can build a common interface as you referred to on julia-users?

Perhaps a separate organization?

**Comment by simonbyrne** [comment]
I'd be happy to. I don't have admin rights to JuliaLang though. Is there an easy way to do this?

**Comment by ViralBShah** [comment]
I've given you admin rights temporarily. Now you can do the transfer.

**Comment by simonbyrne** [comment]
Done. You can change them back now.

**Comment by ViralBShah** [comment]
Thanks.
