### ISSUE TITLE
AppleAccelerate.exp() operation on Complex{Float64} not possible

### ISSUE THREAD

**Issue by joanwa** [JuliaLang/AppleAccelerate.jl#5]
is it by design that the AppleAccelerate.exp() can not operate on Array{Complex{Float64},1}, only on Array{Float64,1} ?

Just wondering? Would be really great if that would also work!

**Comment by simonbyrne** [comment]
Accelerate doesn't provide any complex math functions ([see the full list](https://developer.apple.com/library/mac/documentation/Performance/Conceptual/vecLib/index.html#//apple_ref/doc/uid/TP40002498)).

There is a `cis` function though, which at least gets you part of the way there.
